### ISSUE TITLE
sequelize6 outDir/relations.js import uses filename prefix 'public-' instead of 'public.'; and the imports skip extension

### ISSUE THREAD

**Issue by tuhinpaul** [ozum/pg-generator#100]
### Setup
I am using {"type": "module"} in the package.json file of my Node.js project. And generated models using command:
`pgen example:sequelize6 --contextFile ./pgen-context.json --database $PGDATABASE --user $PGUSER --password $PGPASSWORD --out-dir $modelsDir --clear`
Contents of ./pgen-context.json:
```json
{
  "global": {
    "addSchemaName": false
  }
}

```
### Issues
- In the generated models directory (outDir), the import statements in relations.js file look like:
`import User from "./public-user";`
But the corresponding model filename is public.user.js (dot vs dash)

- The import also skips the extension.

- Moreover, the generated models have this line:
`import sequelize from "../sequelize"; // Provide your own sequelize instance.`
As of now, using default settings for `{"type": "module"}` in Node.js should require using an extension for the filename.

**Comment by ozum** [comment]
@tuhinpaul, as stated in the docs of `pg-generator-example`:

> As indicated following generators are just examples to help you to build yours. Besides personal opinions, every ORM requires careful practices. As a result, we can't maintain ORM codes we are not using. Therefore, see them as a good effort. Even they are not guaranteed to work with current versions of the respective ORM library.

I'm not familiar with sequelize, so helping with it is beyond my knowledge. You should use the given example as a starting point and provide your own template.

**Comment by ozum** [comment]
If you develop your own sequelize template and publish it with npm, I can list your template in the pg-generator docs.

**Comment by tuhinpaul** [comment]
It seems to be an issue in the templates of `pg-generator-example` package. Will check further.

**Comment by tuhinpaul** [comment]
I think this issue may be closed here. I tweaked the default template in pg-generator-example; and getting things okay. This issue should be created in the `pg-generator-example` repo.
