### ISSUE TITLE
sequelize defaultScope

### ISSUE THREAD

**Issue by prokoptsev** [ozum/pg-generator#18]
Hi. I asked about this in [sequelize-pg-generator](https://github.com/ozum/sequelize-pg-generator/issues/2) and you say that I can do it in pg-generator. Could you explain how can I do?
Thanks!

**Comment by ozum** [comment]
Hi,

You can use custom data file. For details please see http://www.pg-generator.com/template/directories-files/ .

In short, you can create a file which exports simple JS object such as:

```js
module.exports = {
    Account: {
        defaultScope: {
            where: {
                active: true
            }
        }
};
```

Then, you can modify default template to access data in this file. All data is copied to template variable named as `custom`. For example `{{ custom.Account.defaultScope.where.active }}`.

You can use for-loops and if conditions to check if given table has defaultScope like below (not tested this example. It may have typos or errors, but it explains the idea)

````
{%- if custom[table.name].defaultScope.include -%}
    {{ custom[table.name].defaultScope.include }}
{% endif -%}
```

**Comment by prokoptsev** [comment]
Ok, got it. I will try.
Thanks.

**Comment by ozum** [comment]
After you completed, if you share a little snippet here for others, that would be great.

**Comment by prokoptsev** [comment]
It's was simpler that I thought. Actually all was in  [{table.name}.js.nunj.html](https://github.com/iozum/pg-generator/blob/v3.0.0/template/sequelize/table/definition/{table.name}.js.nunj.html#L17). 

I added `defaultScope` to custom-date file, as you said, and it's appeared in the model definition.  But because defaultScope it's object it looks like `defaultScope: [object Object]`.

I think about filter something like `JSON.stringify`. Can I add custom filter to generator?

**Comment by ozum** [comment]
Ah yes, I just remembered, `sequelize` template already includes data from custom-data, you don't have to change template.

For `[object Object]` thing, I added `stringifyIfObject` filter to v3.0.1 and updated `sequelize` template to use it by default. This filter lets you print objects directly and if it's input is non-object, does not touch it. I choose to use `require('util').inspect(data, { depth: null })` instead of `JSON.stringify` to make generated code eslint happy.

I published 3.0.1 to npm. Please update it and check whether it helps your situation.

**Comment by prokoptsev** [comment]
Your feedback is impressive!
Thanks :thumbsup:

**Comment by prokoptsev** [comment]
Hi. It turned `util.inspect` is not enough because it does not do string representation a function. But extended options of model may include functions, such as [scope methods](http://sequelize.readthedocs.org/en/latest/docs/scopes/#definition), [class or instance methods](http://docs.sequelizejs.com/en/latest/docs/models-definition/#expansion-of-models).

For example for `custom-data.js`:
```javascript
module.exports = {
  Data: {
    instanceMethods: {
      getDerection: function() {
        return ( this.isRequest ) ? meta.request : meta.response;
      }
    }
  }
}
```
In the generated file, it looks like:
```javascript
    instanceMethods: {
      getDerection: [Function]
    }
```

**Comment by ozum** [comment]
Hmm. I remember, I searched for a decent serializer npm module in the past for something similar, but couldn't find a viable solution which covers every edge case. Do you have any suggestion?

I'm not `sequelize` expert, but for this case, you may also add scopes after a model has been defined by calling `addScope`.
