### ISSUE TITLE
SyntaxError: Unexpected token ...  ---> pg-structure.js:8:19

### ISSUE THREAD

**Issue by nVVEBd** [ozum/pg-generator#19]
Hi,

Installed the package globally and I'm having a problem with running it.

It throws this error:

/Users/blabla/.npm/lib/node_modules/pg-generator/node_modules/pg-structure/lib/db.js:33
        result.schemas = [..._.schemas].map(i => i[1].serialize());
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/blabla/.npm/lib/node_modules/pg-generator/node_modules/pg-structure/lib/pg-structure.js:8:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Any ideas?

//EDIT

Version 2.0.20 works fine.

**Comment by ozum** [comment]
v2 and v3 templates are incompatible, because of changes in `pg-structure` module. Did you regenerate templates with 3.0 and still got error?

**Comment by nVVEBd** [comment]
So npm version 3.0.1 has v2 templates? I'm baffled now.

**Comment by ozum** [comment]
It has nothing to do with npm version. pg-generator v2 templates are incompatible with pg-generator v3 templates.

Reason of error seems spread operator `...`. It is an ES2015 feature and requires --harmony flag in node v4, but you can use it without a flag in node v5.

I will be looking this issue to make it compatible with node v4 without flag.

**Comment by ozum** [comment]
Please update pg-generator to v3.0.2. Problem should be solved now. Waiting for your feedback about this issue.

**Comment by nVVEBd** [comment]
Yeah I saw the ... ecma6 operator and tried to trick it with babel recompiling but didn't have the time to finish the job. Will try it monday and you get feedback right early in the morning.

Thanks for the quick patching!

**Comment by nVVEBd** [comment]
I updated the generator to 3.0.2 and it works like a charm. You should consider adding 

```
try {
    var pg  = require('pg').native || require('pg');
} catch (err) {
    pg      = require('pg');
}
```

to pg-structure for the time being. Or it throws Client not existing error...

But the update solved the problem :+1:
