### ISSUE TITLE
change relations type

### ISSUE THREAD

**Issue by prokoptsev** [ozum/pg-generator#21]
Hi.
I have such a schema (simplified):
```sql
CREATE TABLE person (
  id bigint NOT NULL,
  firstname character varying(250),
  lastname character varying(250),
  CONSTRAINT pk_person PRIMARY KEY (id)
)
CREATE TABLE employment (
  id bigint NOT NULL,
  agreement character varying(250),
  createdat timestamp without time zone,
  deletedat timestamp without time zone,
  CONSTRAINT pk_employment PRIMARY KEY (id),
  CONSTRAINT fk_employment_person FOREIGN KEY (id)
      REFERENCES person (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
```
`pg-generator` detects it as **One-To-Many**:
```
Person.hasMany(Employment, {
    as:         'FkEmploymentPeople',
    foreignKey: 'id',
    onDelete:   'NO ACTION',
    onUpdate:   'NO ACTION'
});
```
But actually is **One-To-One** relations. When I used `sequelize-pg-generator`, I add person.js in `definition-files-custom` and wrote:
```javascript
...
util.getRelation("Employment").type = "belongsTo";
```
How can I do something like with `pg-generator`?

**Comment by ozum** [comment]
`pg-generator` did not support one to one relations, because it is impossible to distinguish automatically `one to one` relations from `one to many` relations.

I updated `pg-generator` to v3.1.0 to support one to one relations. I also added this to [documentation](http://www.pg-generator.com/builtin-templates/sequelize/)

From v3.1.0 on, you can add `custom-data.js` entries similar to below:
```js
module.exports = {
    Company: {
        hasOne: {
            FkEmploymentPerson: {}
        }
    }
};
```

I will appreciate your feedback on this.

**Comment by prokoptsev** [comment]
Thank you again for your help!

**Comment by piyush-banknovo** [comment]
@ozum I am trying to implement the hasOne hack in my project but it does not seem to be working for me. 
Here is my code :
--- Account.js
accounts.hasMany(limits, {
        as: 'LimitsAccountIdFkeys',
        foreignKey: 'account_id',
        onDelete: 'SET NULL',
        onUpdate: 'CASCADE'
    });

-- custom-data.js
accounts:{
        attributes: {
            id: {
                default: 'DataTypes.UUIDV4'
            }
        },
        hasOne: {
            LimitsAccountIdFkeys: {}
        }
    },

Am I doing anything wrong? Why hasMany is generated instead of hasOne?

**Comment by ozum** [comment]
@piyush-banknovo could you please provide a sample repo including DDL script to create DB.
