### ISSUE TITLE
Windows path separator breaking regular expression in exec

### ISSUE THREAD

**Issue by IoannesPaulus** [ozum/pg-generator#25]
Running ```pgen exec``` gives the following error on Windows because of the backslash path separator.

```
error: SyntaxError: Invalid regular expression: /^(.+?)\/: \ at end of pattern
    at new RegExp (native)
    at C:\Users\janos.pal\AppData\Roaming\npm\node_modules\pg-generator\lib\inde
x.js:159:35
    at C:\Users\janos.pal\AppData\Roaming\npm\node_modules\pg-generator\lib\inde
x.js:156:20
    at process._tickCallback (node.js:369:9)
```

**Comment by ozum** [comment]
Hi,

@IoannesPaulus, I updated regular expression with additional backslash. I think it should work in windows now. Since I don't have windows, I cannot test it. Could you please provide feedback if it works or not?

**Comment by IoannesPaulus** [comment]
Hey,

Thanks, it seems to be working just fine now! Thanks for the quick turnaround once again!
