### ISSUE TITLE
How to correctly initialize the database

### ISSUE THREAD

**Issue by yucerjs** [ozum/pg-generator#26]
I have seen in the documentation:

`python
var model  = require('./model/index.js').init(sequelize); // You only need to init once. You can just require later.
`
When I replay that command individually everything works OK.

But when I include it into a Nodejs app it says:
  
`require(..).init is not a function`

Which is the correct way to initialize it inside a nodejs app?

**Comment by ozum** [comment]
You should only call `init` only once in you application. Later, after it is initialized, you just require without `init`. I also updated documentation as below:

From [http://www.pg-generator.com/builtin-templates/sequelize/](http://www.pg-generator.com/builtin-templates/sequelize/)

```js
var Sequelize   = require('sequelize');
var sequelize   = new Sequelize('database', 'user', 'password', { dialect: 'postgres', logging: false });
var model       = require('./model/index.js').init(sequelize); // You only need to init once. You can just require later.

model.Company.findOne({ where: {id: 1} })
    .then(function(company) {
        console.log(company.name);
    })
    .catch(function(error) {
        console.log(err.stack);
    });
```

After you initialized your model, you shouldn't initialize it again and just require your model like below:
  
```js
var model = require('./model/index.js');    // No init here, because it is initialized before.

// Your code here.
```

In addition to this you also can modify templates according to your taste. For example you can change `sequelize-template-folder/db/index.js.nunj.html` file according to your needs and use generated sequelize model files completely different than default. My colleagues usually use modified templates in our projects. However I included sample default templates in `pg-generator` for ease of use.
