### ISSUE TITLE
How to override a single relation name?

### ISSUE THREAD

**Issue by wuher** [ozum/pg-generator#29]
I can see the three options in the [docs](http://www.pg-generator.com/builtin-templates/sequelize/#i-hate-aliases-that-sequelize-template-generate-what-can-i-do). I would like to use the second option of the three. 

In the docs:

    Account: {
        hasMany: {
            HasContacts: {
                as: 'MyBeautifulAlias'
            }
        },

`Account` is the name of the model, `hasMany` is the type of the relationship and `as: 'MyBeautifulAlias` assigns my desired alias, but where does `HasContacts` come from? What should I put there?

I am trying to figure out how to override the name for a single `hasMany` relationship in my own schema. I had it working with `sequelize-pg-generator` but that format is probably not supported anymore.

Thank you

**Comment by ozum** [comment]
Hi,

Documentation needs some light here. I updated documentation and `relation-cheatsheet.txt` for this. Please first update to latest version.

About your question: `HasContacts` is the alias generated by pgen if you don't override. In given example pgen would have created an alias as `HasContacts`, but you want it to override and rename `HasContacts` as `MyBeautifulAlias`.

You can follow steps below:
1. Generate files without `custom-data.js`.
2. Note alias names you want to rename. You can see all alias names in `relation-cheatsheet.txt` file. (for example: `HasContacts`).
3. Use noted alias names you want to rename in `custom-data.js` file and provide your desired alias name.

I hope it is clarified now.

I need some help here in documentation form someone else's point of view. If you document this in a couple of lines for other users, please send a PR or write here I will update documentation.

**Comment by wuher** [comment]
Thanks,

I finally got back to this and was able to resolve the naming issue. One thing I was missing the fact that desired relation name needs to be double quoted (e.g. `"'myAlias'"`).

I have another question though. How about if I also want to change, not just the name, but also the type of the relationship from `hasMany` to `hasOne`?

I can see [this](http://www.pg-generator.com/builtin-templates/sequelize/#relations) in the docs but I can't figure out how to change both, the type and the name of a relationship.

Thanks

**Comment by ozum** [comment]
Sorry, it is a limitation of current design and not possible to change both at the same time.
