### ISSUE TITLE
unnecessary spaces are inserted and html is breaking 

### ISSUE THREAD

**Issue by fedevela** [ozum/pg-generator#30]
hello!

I am trying to generate some react html but strange spaces are inserted breaking the html.

Please help!!!!

using the base template

running with command
`pgen exec pg-generator-templates/react-crud-template/ -d convectorFeathersServer -u postgres -p postgres -t src/react-crud-build`

my template file :

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
    <title>React App</title>
  </head>
  <body>
    <div id="root"></div>
    <script src="bundle.js"></script>
  </body>
</html>

```

the result

```
< !doctype html >
    <
    html lang = "en" >
    <
    head >
    <
    meta charset = "utf-8" >
    <
    meta name = "viewport"
content = "width=device-width, initial-scale=1" >
    <
    link rel = "stylesheet"
href = "https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css" >
    <
    title > React App < /title> <
    /head> <
    body >
    <
    div id = "root" > < /div>
    <
    script src = "bundle.js" > < /script> <
    /body> <
    /html>

```

**Comment by ozum** [comment]
Hi,

That's strange. Maybe `js-beautify` used by pg-generator could be reason.

Could you please comment line 119 - 121 of `lib/index.js`

```js
       if (path.extname(target) === '.js' || path.extname(target) === '.html') {
            content         = beautify(content, this.beautyOptions);
        }
```

```js
      // if (path.extname(target) === '.js' || path.extname(target) === '.html') {
      //      content         = beautify(content, this.beautyOptions);
      //  }
```

`content` in that function is generated text to be written to file. Please report result back, so I can figure something to fix that.

**Comment by fedevela** [comment]
hi thank you for your reply, im sorry but i do not understand where to make the change, that would be where pg-generator was installed in my global packages???

**Comment by ozum** [comment]
Yes that is the where pg-generator is installed globally. In pg-generator directory lib/index.js file.

**Comment by fedevela** [comment]
OK that fixed the issue!!!!!

my node modules folder on linux was

~/.nvm/versions/node/v5.10.1/lib/node_modules/pg-generator

thank you very much!!!!!

**Comment by fedevela** [comment]
i guess this would be an ideal candidate for a command line parameter

**Comment by ozum** [comment]
@fedevela, I added `--nobeautifier` CLI option, which prevents beautifier. I uploaded to Git and NPM.

Please update to latest version via npm.

**Comment by fedevela** [comment]
Thank you so much for your quick response and for pg-generator which i find to be absolutely amazing!!!!!

**Comment by ozum** [comment]
Thank you.

Özüm Eldoğan




On Wed, Jul 27, 2016 at 9:07 PM +0300, "Federico Vela" <notifications@github.com> wrote:












Thank you so much for your quick response and for pg-generator which i find to be absolutely amazing!!!!!
