### ISSUE TITLE
Exporting comments breaks the model definition files

### ISSUE THREAD

**Issue by evoye** [ozum/pg-generator#31]
Hi Ozum,

first of all, thanks for the great work, it saved me a lot of time :)

In my case I have used comments on database fields, tables or schemas, which break the exported module definition files. The reason is, that the comments usually contain line breaks or other special characters, that get rendered 1:1 and thus break the JavaScript definition object.

E.g.

return sequelize.define('tablename', {
        firstField: {
            type: DataTypes.BIGINT,
            field: 'id_ad_profile',
            allowNull: false,
            primaryKey: true,
            autoIncrement: true,
            comment: 'first line of field comment
second line
'
        },
       comment:'first line of table comment
second line
'
})

Maybe, there is an easy way to just not export comments by default.
This would avoid fixing the exported files manually afterwards.

Thanks

**Comment by ozum** [comment]
Hi,

Thanks for reporting. I submit an update. Multi line comments are replaced with corresponding escape characters now.

Please update to `3.4.2`.

Best Regards,

**Comment by evoye** [comment]
works great.
Thanks
