### ISSUE TITLE
There's no --ssl flag?

### ISSUE THREAD

**Issue by gbahamondezc** [ozum/pg-generator#35]
I'm wondering if there's is a way to make SSL connections, some databases needs SSL=on.

I was looking the code a bit, but i can't find some kind of  ```--ssl``` flag to set connection as SSL.

**Comment by ozum** [comment]
Hi,

You are right, SSL seems missing in CLI.

I added `--ssl` options to CLI. However I don't have a DB to test `--ssl`. Could you please check if it is working and report back?

Best,

**Comment by gbahamondezc** [comment]
@ozum i tested, but was not working i think you forgot add the SSL as a key in simpleOptions, so,  i sent a **PR**  #36 with the fix. 👍

**Comment by ozum** [comment]
I merged PR and updated github and npm. Thanks.
