### ISSUE TITLE
Problem in custom model file when a model has multiple relationships

### ISSUE THREAD

**Issue by ignotus0001** [ozum/pg-generator#37]
Hi, I believe I've discovered a bug with the aliasing of hasMany relationship in the custom model file. It may occur for belongsTo and other types of relationships as well, I don't know. Anyway, here's an example:

```
    Vehicle: {
        timestamps: true,
        hasMany: {
            AdditionalSpaceConfigurationsVehicleidFkeys: {
                as: '\'additionalSpaceConfigurations\''
            }
        },
        hasMany: {
            AttributesVehicleidFkeys: {
                as: '\'attributes\''
            }
        },
        hasMany: {
            SeatConfigurationsVehicleidFkeys: {
                as: '\'seatConfigurations\''
            }
        }
    },
```
So you can see this Vehicle table (in a Postgres database) has FKs to multiple tables, and I'm trying to override the names of all of them. But only the LAST one results in changes in the generated model file; in the above example it's "seatConfigurations". If I change the order so that "attributes" is physically last in the object definition, then it works but "seatConfigurations" reverts to "SeatConfigurationsVehicleidFkeys", and so on.

By the way, I couldn't make anything work at all here if I didn't add extra single quotes to the value of the "as" property. Is there some change I can make to the template file to fix that? I tried but was unsuccessful, and I don't have time to learn nunJucks in detail.

Thanks,

Billy B

**Comment by ignotus0001** [comment]
I forgot to mention ... I also tried as a single collection

```
    Vehicle: {
        timestamps: true,
        hasMany: [
            {
                AdditionalSpaceConfigurationsVehicleidFkeys: {
                as: '\'additionalSpaceConfigurations\''
                }
            },
            {
                AttributesVehicleidFkeys: {
                    as: '\'attributes\''
                }
            },
            {
                SeatConfigurationsVehicleidFkeys: {
                    as: '\'seatConfigurations\''
                }
            }
        ]
    },
```
But it didn't work at all. None of them were overridden

**Comment by ignotus0001** [comment]
OK. 3rd time is the charm; I found the answer myself. Don't know why I didn't try it earlier. This works:
```
    Vehicle: {
        timestamps: true,
        hasMany: {
            AdditionalSpaceConfigurationsVehicleidFkeys: {
                as: '\'additionalSpaceConfigurations\''
            },
            AttributesVehicleidFkeys: {
                as: '\'attributes\''
            },
            SeatConfigurationsVehicleidFkeys: {
                as: '\'seatConfigurations\''
            }
        }
    },
```
I still wouldn't mind knowing if there's a solution for the double quoting issue, however.

**Comment by ozum** [comment]
You need to double quote, see my explanation about quotes in https://github.com/ozum/pg-generator/issues/34#issuecomment-255977184.

**Comment by ignotus0001** [comment]
Got it. And apologies for wasting your time with the multiple relationships issue. Dunno what took me so long!

**Comment by ozum** [comment]
Not problem at all.
