### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by roytz** [ozum/pg-generator#45]
Hi,
I have a schema that uses the `uuid-ossp` extension in order to generate uuid as default value -
```
CREATE TABLE IF NOT EXISTS public."SomeTable"
(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ...
)
```

but the generated model I get is with no default value settings.
I also use empty array as default on some schemas but it also not generated into the model created by pg-generator.
Am I missing something?

Thank you!

**Comment by andresmeidla** [comment]
Got the same problem,
worked around it with defining custom attribute with the datafile option "--datafile custom.js"
custom.js
```
// template customizations
const customers = {
    attributes: {
        id: {
            default: 'DataTypes.UUIDV4'
        }
    }
};

var custom = {
    Customer: customers
}

module.exports = custom;

```

**Comment by ozum** [comment]
Currently, extension support is limited (read: non exists). You may use @andresmeidla's workaround.
