### ISSUE TITLE
Skip Tables

### ISSUE THREAD

**Issue by philberg** [ozum/pg-generator#46]
I'm using PostGis, which creates several tables that I don't want to generate models for.

Is there an option to skip specific tables?  It looks like the old library had this.

**Comment by jhairau** [comment]
@philberg I used the code below to place my PostGis related tables (incompatible with PG-Structure) out of the `public` schema into their own schema `postgis`.

```
CREATE SCHEMA postgis;
ALTER TABLE geography_columns SET SCHEMA postgis;
ALTER TABLE geometry_columns SET SCHEMA postgis;
ALTER TABLE raster_columns SET SCHEMA postgis;
ALTER TABLE raster_overviews SET SCHEMA postgis;
ALTER TABLE spatial_ref_sys SET SCHEMA postgis;
```

**Comment by ozum** [comment]
Unfortunately, it doesn't have this feature. Added as a feature request.

**Comment by ozum** [comment]
By the way, it is harder than I expected.

Implementation must

- consider tables to skip,
- consider all references, foreign keys etc. referencing to skipped tables have to be handled accordingly, since there isn't a model for the skipped table.
