### ISSUE TITLE
No option to set underscored: true for sequelize models

### ISSUE THREAD

**Issue by piyush-banknovo** [ozum/pg-generator#55]
I am using underscored convention for model columns. Is it possible to set underscored:true for sequelize while generating models?

**Comment by ozum** [comment]
I guess you mean underscored JS objects.

For that, you can modify sample generated sequelize template according to your needs.

Please see http://www.pg-generator.com/template/filters/ for filters related to casing. Modify filters used in template, and use your modified template to generate models.

**Comment by piyush-banknovo** [comment]
Thanks @ozum. I was expecting underscored:true|false option in file: {table.name # dashCase}.js.nunj.html where options schema, tableName and timestamps are present. However, I can add underscored:true from customFile.js. So, issue can be closed.
