### ISSUE TITLE
Template not compatible with latest version of sequelize@6.2.4

### ISSUE THREAD

**Issue by devansvd** [ozum/pg-generator#69]
Sequelize import is not a function. I guess sequelize.import is deprecated in latest version 6.2.4.
Postgres: 9.6
```
model.User = sequelize.import('./definition/user.js');
                                    ^
TypeError: sequelize.import is not a function
```
This works after removing sequelize.import with require then receive next error.

User hasMany is not a function.
```
User.hasMany(Product, {
            ^
TypeError: User.hasMany is not a function
```
Template not compatible with latest version of sequelize@6.2.4.

**Comment by ozum** [comment]
Hi,

Templates are provided as an example for users develop their owns.. Unfortunately, I cannot keep an eye on all ORM's continuously.

However, if you like you can create a PR to update relevant template and its docs.

**Comment by devansvd** [comment]
@ozum thanks for the reply, what you're saying is a valid point. Couldn't able to spend much time will figure it out. Thanks for developing this. I have been using this for the past three years. So good. Apologize for the delayed response.
