### ISSUE TITLE
Some relations have same names

### ISSUE THREAD

**Issue by j2l** [ozum/pg-generator#93]
Hi!
First of all, congrats for your gems! pg-generator and pg-structure seem great!

I'm testign some use-cases.
For basic postgres tables, I can make it work using alpha: `pgen example:sequelize6 --out-dir models --clear --relation-name-functions descriptive --i public`

But when using a backend like [slatcorn](https://github.com/saltcorn/saltcorn), pg-generator can't name relations: 
```
Some relations have same names. Use "optimal" or "descriptive" for "relationNameFunctions" option or proivde your own naming functions.
{
  'public._sc_fields': {
    m2o: [],
    o2m: [],
    m2m: [
      {
        ScRoles: [
          '[public._sc_fields]――― _sc_tables_ownership_field_id_fkey ――⥷ [public._sc_tables] ⭃―― public._sc_tables._sc_tables_min_role_read_fkey ―――[public._sc_roles]',
          '[public._sc_fields]――― _sc_tables_ownership_field_id_fkey ――⥷ [public._sc_tables] ⭃―― public._sc_tables._sc_tables_min_role_write_fkey ―――[public._sc_roles]'
        ]
      }
    ]
  },
  'public._sc_roles': {
    m2o: [],
    o2m: [
      {
        ScRolesScTables: [
          '[public._sc_roles]――― _sc_tables_min_role_read_fkey ――⥷ [public._sc_tables]',
          '[public._sc_roles]――― _sc_tables_min_role_write_fkey ――⥷ [public._sc_tables]'
        ]
      }
    ],
    m2m: [
      {
        ScRoles: [
          '[public._sc_roles]――― _sc_tables_min_role_read_fkey ――⥷ [public._sc_tables] ⭃―― public._sc_tables._sc_tables_min_role_write_fkey ―――[public._sc_roles]',
          '[public._sc_roles]――― _sc_tables_min_role_write_fkey ――⥷ [public._sc_tables] ⭃―― public._sc_tables._sc_tables_min_role_read_fkey ―――[public._sc_roles]'
        ]
      },
      {
        ScRolesScFields: [
          '[public._sc_roles]――― _sc_tables_min_role_read_fkey ――⥷ [public._sc_tables] ⭃―― public._sc_tables._sc_tables_ownership_field_id_fkey ―――[public._sc_fields]',
          '[public._sc_roles]――― _sc_tables_min_role_write_fkey ――⥷ [public._sc_tables] ⭃―― public._sc_tables._sc_tables_ownership_field_id_fkey ―――[public._sc_fields]'
        ]
      }
    ]
  },
  'public._sc_tables': {
    m2o: [
      {
        ScRole: [
          '[public._sc_tables] ⭃―― _sc_tables_min_role_read_fkey ―――[public._sc_roles]',
          '[public._sc_tables] ⭃―― _sc_tables_min_role_write_fkey ―――[public._sc_roles]'
        ]
      }
    ],
    o2m: [],
    m2m: []
  }
}
```
Here's _sc_fields:
![image](https://user-images.githubusercontent.com/65325/163991390-e46accc2-cd7b-4be8-9096-f5219ebfa196.png)

Since, these are internal tables, I can't manually rename them without breaking everything.

Actually, I'd like to exclude some tables but `gen example:sequelize6 --out-dir models --clear --relation-name-functions descriptive -e public._sc_%` doesn't exclude these tables.
Any idea?

And, if I have to keep them, I don't get how to provide naming functions.

**Comment by ozum** [comment]
Hi @j2l,

You don't need to rename your tables. As you discovered, you should use your own naming functions, because it is impossible to generate unique names in complex scenarios.

1. Create a JS file that exports 3 functions: `o2m`, `m2o`, and `m2m`. Name the file as you wish. For example "my-naming-functions.js"
2. Write the path of your js file to the options: `pgen example:sequelize6 --out-dir models --clear --relation-name-functions ./my-naming-functions.js --i public`

For other details such as what parameters are provided and what those parameters contain etc. you should read below:
https://www.pg-generator.com/nav.01.guide/02.advanced.html#relation-names
https://www.pg-structure.com/nav.02.api/#relationnamefunctions

**Comment by j2l** [comment]
Thank you @ozum !
Any chance to be able to exclude tables using the CLI command?

**Comment by ozum** [comment]
Unfortunately, only schemas can be included or excluded.

**Comment by ozum** [comment]
Why you may ask... It is very hard to track orphan relationships if some of the tables are excluded. At least for the current architecture...

**Comment by j2l** [comment]
OK, thanks for taking the time to explain.
Closing this one.
